### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Sewdohe** [CachyOS/CachyOS-Emerald-KDE#1]
Are we supposed to use the package manager to install this somehow or just move the folders to the correct places?

I could maybe write an install script if need be.

**Comment by ptr1337** [comment]
Sorry for the late answer. I did not see that you have written here.

You can simply install it with pacman via `sudo pacman -S cachyos-emerald-kde-git`.
Or you can move the files into the proper path.

**Comment by Sewdohe** [comment]
Thanks for the response! I've already gotten the same one from you on the Telegram chat :b I'm more interested in someone responding with the instructions to add an icon to the cachyos-char-white icon pack. I've made around 10 icons to add to the pack because I can't stand for my icons to look different, but I can't figure out how to make them colorize like the icons that come in the pack. 

I'd love to get all these colorized and make a PR to the cachy icon-pack!
